# Generated by Django 4.0.3 on 2022-05-28 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_article_image_alter_article_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=20, verbose_name='İsim...')),
                ('comment_content', models.CharField(max_length=5000, verbose_name='yorum...')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.article', verbose_name='makale')),
            ],
        ),
    ]
